# configs/params_overfit_exp3.yaml
data:
  train:  "VisDroneTractor-4/train.txt"
  val:    "VisDroneTractor-4/valid.txt"
  config: "VisDroneTractor-4/data.yaml"

# -------------------------------------------------------------------
# Model
# -------------------------------------------------------------------
model:
  name:    "YOLOv9"
  weights: "yolov9m.pt"
  anchor:
    auto:    false        # пересчёт анкоров под вашу выборку

# -------------------------------------------------------------------
# Training Setup
# -------------------------------------------------------------------
training:
  epochs:         270
  batch:          16
  accumulate:     2
  imgsz:          672
  device:         "cuda:0"
  amp:            true
  norm:           "GroupNorm"
  norm_groups:    32

  optimizer:
    type:         "SGD"
    lr:           0.008
    momentum:     0.937
    weight_decay: 0.0005

  lr_scheduler:
    type:         "OneCycleLR"
    max_lr:       0.02
    pct_start:    0.1
    anneal_strategy: "cos"

  warmup_bias_lr: true

  curriculum:
    start_epoch:  10
    end_epoch:    90
    mosaic_max:   0.9
    mixup_max:    0.5
    ra_max_ops:   4
    ra_magnitude: 10

  multi_scale:    true
  ms_range:
    - 0.5
    - 1.5

# -------------------------------------------------------------------
# Augmentations
# -------------------------------------------------------------------
augment:
  policy:         "RandAugment"
  ra_n:           3
  ra_m:           10

  cutmix:
    enabled:      true
    prob:         0.6
    target_class: "people"
    high_res:     true

  random_perspective:
    degrees:      10

  brightness_contrast:
    brightness:   0.3
    contrast:     0.3

# -------------------------------------------------------------------
# Loss
# -------------------------------------------------------------------
loss:
  type:           "Combo"
  iou:            "SIoU"
  focal_gamma:    2.0
  cls_pw:         3.0
  box_pw:         0.05
  small_obj_weight: 2.0
  label_smoothing:  0.2

# -------------------------------------------------------------------
# Dataloader: balancing / mining / tiling
# -------------------------------------------------------------------
dataloader:
  oversample:
    class:        "people"
    factor:       3
  hard_mining:
    enabled:      true
    iou_threshold: 0.5
    mining_ratio: 0.25
  tiling:
    enabled:      true
    size:         512
    overlap:      64

# -------------------------------------------------------------------
# SWA
# -------------------------------------------------------------------
swa:
  enabled:        true
  start_epoch:    240
  swa_freq:       2

# -------------------------------------------------------------------
# Hyperparameter Evolution
# -------------------------------------------------------------------
evolve:
  enabled:        true
  generations:    20
  population:     30
  mutate_rate:    0.9

# -------------------------------------------------------------------
# Test-Time Augmentation & Inference
# -------------------------------------------------------------------
tta:
  enabled:        true
  tile_infer:     true
  scales:
    - 0.75
    - 1.0
    - 1.25
  flips:
    - "horizontal"
    - "vertical"

postproc:
  conf_threshold: 0.34
  nms_iou_threshold: 0.50

# -------------------------------------------------------------------
# Output
# -------------------------------------------------------------------
output:
  metrics:        "metrics_overfit_exp3.json"
