# -----------------------------------------------------------------------------
# Data & Model
# -----------------------------------------------------------------------------
data:
  train:  "VisDroneTractor-4/train.txt"
  val:    "VisDroneTractor-4/valid.txt"
  config: "VisDroneTractor-4/data.yaml"

model:
  name:    "YOLOv9"
  weights: "yolov9m.pt"
  anchor:
    auto:    true        # пересчёт анкоров под вашу выборку

# -----------------------------------------------------------------------------
# Training Schedule & Optimizer
# -----------------------------------------------------------------------------
training:
  epochs:             260
  batch:              16
  accumulate:         2
  imgsz:              640
  device:             "cuda:0"
  amp:                true
  optimizer:
    type:             "SGD"
    lr:               0.01
    momentum:         0.937
    weight_decay:     1e-4
  lr_scheduler:
    type:             "OneCycleLR"
    max_lr:           0.02
    pct_start:        0.1
    anneal_strategy:  "cos"
  warmup_bias_lr:     true

  # Curriculum learning: плавный рост аугментаций
  curriculum:
    start_epoch:      20
    end_epoch:        80
    mosaic_max:       0.8
    mixup_max:        0.4
    ra_max_ops:       3    # RandAugment: макс. операций
    ra_magnitude:     9    # RandAugment: сила аугментации

# -----------------------------------------------------------------------------
# Augmentations
# -----------------------------------------------------------------------------
augment:
  # вместо статического mosaic/mixup — RandAugment или AutoAugment
  policy:             "RandAugment"  # or "AutoAugment"
  ra_n:               2              # число операций
  ra_m:               9              # сила
  cutmix:
    enabled:          true
    prob:             0.5
    target_class:     "people"
    high_res:         true
  random_perspective:
    degrees:          15
  brightness_contrast:
    brightness:       0.2
    contrast:         0.2

# -----------------------------------------------------------------------------
# Losses & Label Smoothing
# -----------------------------------------------------------------------------
loss:
  type:              "SIoU"
  alpha:             3.0
  focal_gamma:       2.0
  cls_pw:            3.0
  box_pw:            0.05
  label_smoothing:   0.1

# -----------------------------------------------------------------------------
# Class balancing & mining
# -----------------------------------------------------------------------------
dataloader:
  oversample:
    class:            "people"
    factor:           2
  hard_mining:
    enabled:          true
    iou_threshold:    0.5
    mining_ratio:     0.2

# -----------------------------------------------------------------------------
# SWA (Stochastic Weight Averaging)
# -----------------------------------------------------------------------------
swa:
  enabled:            true
  start_epoch:        230
  swa_freq:           5

# -----------------------------------------------------------------------------
# Automatic Hyperparameter Evolution
# -----------------------------------------------------------------------------
evolve:
  enabled:            true
  generations:        10
  population:         20
  mutate_rate:        0.8

# -----------------------------------------------------------------------------
# Test-Time Augmentation & Inference
# -----------------------------------------------------------------------------
tta:
  enabled:            true
  scales:             [0.75, 1.0, 1.25]
  flips:              ["horizontal", "vertical"]

postproc:
  conf_threshold:     0.34
  nms_iou_threshold:  0.50

# -----------------------------------------------------------------------------
# Output
# -----------------------------------------------------------------------------
output:
  metrics:            "metrics_overfit.json"
